# FBA-Bench Docker Compose Configuration
# This file defines the services for the FBA-Bench LLM benchmarking tool

version: '3.8'

services:
  fba-bench:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fba-bench
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./scenario_results:/app/scenario_results
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - API_HOST=0.0.0.0
      - API_PORT=8000
    restart: unless-stopped
    networks:
      - fba-bench-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Redis for caching and session management
  redis:
    image: redis:7-alpine
    container_name: fba-bench-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - fba-bench-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: PostgreSQL for persistent data storage
  postgres:
    image: postgres:15-alpine
    container_name: fba-bench-postgres
    environment:
      POSTGRES_DB: fba_bench
      POSTGRES_USER: fba_bench_user
      POSTGRES_PASSWORD: fba_bench_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - fba-bench-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fba_bench_user -d fba_bench"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: fba-bench-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fba-bench
    restart: unless-stopped
    networks:
      - fba-bench-network

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local

networks:
  fba-bench-network:
    driver: bridge