version: "3.9"

services:
  api:
    image: python:3.11-slim
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      AUTH_ENABLED: "false"
      AUTH_TEST_BYPASS: "true"
      FBA_CORS_ALLOW_ORIGINS: "*"
      DATABASE_URL: "sqlite+aiosqlite:///./dev.db"
      DB_AUTO_CREATE: "true"
      API_RATE_LIMIT: "100/minute"
      LOG_LEVEL: "INFO"
    volumes:
      - ./:/app
    command: >
      sh -c "pip install --no-cache-dir poetry==1.7.1 &&
             poetry config virtualenvs.create false &&
             poetry install --no-interaction --no-ansi &&
             uvicorn fba_bench_api.main:create_app --factory --host 0.0.0.0 --port 8000 --reload"

  frontend:
    image: node:18-alpine
    working_dir: /app/frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: "http://localhost:8000"
      VITE_WS_URL: "ws://localhost:8000"
      VITE_REALTIME_URL: "ws://localhost:8000/ws/realtime"
      VITE_AUTH_ENABLED: "false"
      CI: "true"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - api
    command: >
      sh -c "npm ci && npm run dev -- --host 0.0.0.0"