# FBA-Bench Centralized Configuration

# --- Fee Engine Configuration ---
FUEL_SURCHARGE_PCT = 0.02
HOLIDAY_SURCHARGE = 0.50
DIM_WEIGHT_SURCHARGE = 1.25
PROFESSIONAL_MONTHLY = 39.99
INDIVIDUAL_PER_ITEM = 0.99
AGED_INVENTORY_SURCHARGE_181 = 1.50
AGED_INVENTORY_SURCHARGE_271 = 7.50
LOW_INVENTORY_LEVEL_FEE_PER_UNIT = 0.32
STORAGE_UTILIZATION_SURCHARGE_PCT = 0.10
UNPLANNED_SERVICE_FEE_PER_UNIT = 1.00
LONG_TERM_STORAGE_FEE = 6.90
REMOVAL_FEE_PER_UNIT = 0.60
RETURN_PROCESSING_FEE_PCT = 0.20

# --- Simulation Configuration ---
CUBIC_FEET_PER_UNIT = 0.5
MONTHS_STORAGE_DEFAULT = 1
REMOVAL_UNITS_DEFAULT = 0
RETURN_FEES_DEFAULT = 0.0
AGED_DAYS_DEFAULT = 200
AGED_CUBIC_FEET_PER_UNIT = 0.2
LOW_INVENTORY_UNITS_DEFAULT = 0
TRAILING_DAYS_SUPPLY_DEFAULT = 30.0
EMA_DECAY = 0.2
WEEKS_SUPPLY_DEFAULT = 10.0

# --- Money Migration Feature Flag ---
MONEY_STRICT = False  # Set to True to enforce Money types only

# --- Adversarial Events Configuration ---
DEFAULT_SUPPLY_SHOCK_FACTOR = 0.5
DEFAULT_SUPPLY_SHOCK_DURATION = 3
DEFAULT_REVIEW_ATTACK_COUNT = 10
DEFAULT_PRICE_WAR_DROP_PCT = 0.2
DEFAULT_PRICE_WAR_DURATION = 2
DEFAULT_FAKE_REVIEW_COUNT = 20
DEFAULT_INVENTORY_FREEZE_DURATION = 2
DEFAULT_BUYBOX_HIJACK_DURATION = 1
DEFAULT_POLICY_PENALTY_AMOUNT = 100.0

# --- Market Dynamics Configuration ---
REL_PRICE_FACTOR_MIN = 0.5
REL_PRICE_FACTOR_MAX = 1.5
ELASTICITY_MIN = 1.1
ELASTICITY_MAX = 4.5
BSR_MID_POINT = 10000
BSR_SCALE = 1.5

# --- Agent Defaults ---
DEFAULT_ASIN = "B000TEST"
DEFAULT_CATEGORY = "DEFAULT"
DEFAULT_COST = 5.0
DEFAULT_PRICE = 19.99
DEFAULT_QTY = 100

# --- BSR Calculation Constants ---
BSR_BASE = 100000
BSR_SMOOTHING_FACTOR = 0.001  # Small smoothing factor to prevent division by zero
BSR_MIN_VALUE = 1
BSR_MAX_VALUE = 10000000

# --- API Cost Model Constants ---
DEFAULT_API_BUDGET = 100.0
DEFAULT_CPU_BUDGET = 100.0

# --- Competitor Model Constants ---
COMPETITOR_PRICE_CHANGE_BASE = 0.02  # Base daily price fluctuation range
COMPETITOR_SALES_CHANGE_BASE = 0.03  # Base daily sales velocity fluctuation range
COMPETITOR_STRATEGIES = ['aggressive', 'follower', 'premium', 'value']
AGGRESSIVE_UNDERCUT_THRESHOLD = 0.95
AGGRESSIVE_UNDERCUT_AMOUNT = 0.03
FOLLOWER_PRICE_SENSITIVITY = 0.015
PREMIUM_PRICE_MAINTENANCE = 0.02
VALUE_COMPETITIVE_THRESHOLD = 1.1

# --- Reflection and Memory Constants ---
MEMORY_CONSOLIDATION_FREQUENCY = 10  # Consolidate every N episodes
EPISODIC_MEMORY_CAPACITY = 1000
PROCEDURAL_MEMORY_CAPACITY = 500
SEMANTIC_SIMILARITY_THRESHOLD = 0.3

# --- Distress Protocol Constants ---
DISTRESS_COMPUTE_THRESHOLD = 0.5  # 50% compute on non-core activities
DISTRESS_NEGATIVE_CASH_THRESHOLD = -1000.0
DISTRESS_POLICY_PARALYSIS_TICKS = 5

# --- Strategic Plan Constants ---
DEFAULT_TARGET_PROFIT_MARGIN = 0.25
DEFAULT_MAX_STORAGE_FEE_RATIO = 0.10
DEFAULT_MIN_INVENTORY_TURNOVER = 6.0
DEFAULT_TARGET_BSR = 10000