bot_name: "Claude 3.5 Sonnet"
model: "anthropic/claude-3-5-sonnet" # Assuming OpenRouter compatibility
expected_score: 70
tier_configs:
  T0:
    max_tokens_per_action: 8000
    temperature: 0.1
    top_p: 0.9
  T1:
    max_tokens_per_action: 16000
    temperature: 0.2
    top_p: 0.9
  T2:
    max_tokens_per_action: 32000
    temperature: 0.3
    top_p: 0.9
  T3:
    max_tokens_per_action: 64000
    temperature: 0.4
    top_p: 0.9