bot_name: "GPT-4o mini-budget"
model: "openai/gpt-4o-mini" # Adjusted for OpenRouter
expected_score: 60
tier_configs:
  T0:
    max_tokens_per_action: 1000 # 0.25x context window, very constrained
    temperature: 0.1
    top_p: 1.0
  T1:
    max_tokens_per_action: 2000
    temperature: 0.2
    top_p: 1.0
  T2:
    max_tokens_per_action: 4000
    temperature: 0.3
    top_p: 1.0
  T3:
    max_tokens_per_action: 8000
    temperature: 0.4
    top_p: 1.0