# Basic benchmark configuration template
# This template provides a simple starting point for benchmarking

benchmark_id: "basic_benchmark"
name: "Basic Benchmark"
description: "A basic benchmark configuration for testing agent performance"
version: "1.0.0"

# Environment configuration
environment:
  deterministic: true
  random_seed: 42
  parallel_execution: false
  max_workers: 1

# Scenarios to run
scenarios:
  - id: "ecommerce_basic"
    name: "Basic E-commerce Scenario"
    type: "ecommerce"
    enabled: true
    priority: 1
    config:
      duration: 100
      complexity: "medium"
      domain: "retail"
      difficulty: "easy"

# Agents to benchmark
agents:
  - id: "diy_agent"
    name: "DIY Agent"
    type: "diy"
    enabled: true
    config:
      agent_type: "advanced"
      strategy: "profit_maximizer"
      price_sensitivity: 0.1
      reaction_speed: 1
      min_price_cents: 500
      max_price_cents: 5000

# Metrics configuration
metrics:
  categories:
    - "cognitive"
    - "business"
    - "technical"
  custom_metrics: []

# Execution configuration
execution:
  runs_per_scenario: 3
  max_duration: 0  # Unlimited
  timeout: 300
  retry_on_failure: true
  max_retries: 3

# Output configuration
output:
  format: "json"
  path: "./results"
  include_detailed_logs: false
  include_audit_trail: true

# Validation configuration
validation:
  enabled: true
  statistical_significance: true
  confidence_level: 0.95
  reproducibility_check: true

# Metadata
metadata:
  author: "FBA-Bench Team"
  created: "2025-01-01T00:00:00Z"
  tags: ["basic", "template", "getting-started"]