# Advanced benchmark configuration template
# This template provides a comprehensive benchmark configuration for thorough testing

benchmark_id: "advanced_benchmark"
name: "Advanced Comprehensive Benchmark"
description: "A comprehensive benchmark configuration for testing multiple agents across various scenarios"
version: "1.0.0"

# Environment configuration
environment:
  deterministic: true
  random_seed: 12345
  parallel_execution: true
  max_workers: 4

# Scenarios to run
scenarios:
  - id: "ecommerce_complex"
    name: "Complex E-commerce Scenario"
    type: "ecommerce"
    enabled: true
    priority: 1
    config:
      duration: 500
      complexity: "high"
      domain: "retail"
      difficulty: "hard"
      market_volatility: 0.3
      competitor_count: 5
  
  - id: "healthcare_diagnosis"
    name: "Healthcare Diagnosis Scenario"
    type: "healthcare"
    enabled: true
    priority: 2
    config:
      duration: 300
      complexity: "high"
      domain: "healthcare"
      difficulty: "expert"
      patient_cases: 50
      accuracy_threshold: 0.95
  
  - id: "financial_analysis"
    name: "Financial Analysis Scenario"
    type: "financial"
    enabled: true
    priority: 3
    config:
      duration: 400
      complexity: "high"
      domain: "finance"
      difficulty: "hard"
      market_data_points: 1000
      risk_factors: 10
  
  - id: "legal_document_review"
    name: "Legal Document Review Scenario"
    type: "legal"
    enabled: true
    priority: 4
    config:
      duration: 350
      complexity: "medium"
      domain: "legal"
      difficulty: "hard"
      document_count: 25
      compliance_requirements: 15

# Agents to benchmark
agents:
  - id: "diy_advanced"
    name: "DIY Advanced Agent"
    type: "diy"
    enabled: true
    config:
      agent_type: "expert"
      strategy: "adaptive_profit_maximizer"
      price_sensitivity: 0.05
      reaction_speed: 2
      min_price_cents: 100
      max_price_cents: 10000
      learning_rate: 0.01
  
  - id: "crewai_agent"
    name: "CrewAI Agent"
    type: "crewai"
    enabled: true
    config:
      llm_config:
        provider: "openai"
        model: "gpt-4"
        temperature: 0.1
        max_tokens: 2000
      agent_config:
        allow_delegation: true
        verbose: false
      crew_config:
        process: "hierarchical"
        manager_llm: "gpt-4"
  
  - id: "langchain_agent"
    name: "LangChain Agent"
    type: "langchain"
    enabled: true
    config:
      llm_config:
        model: "gpt-4"
        temperature: 0.1
      memory_config:
        type: "buffer"
        window_size: 20
      max_iterations: 10
      verbose: false

# Metrics configuration
metrics:
  categories:
    - "cognitive"
    - "business"
    - "technical"
    - "ethical"
  custom_metrics:
    - name: "adaptability_score"
      type: "cognitive"
      config:
        measurement_interval: 10
        baseline_performance: 0.7
    - name: "resource_efficiency"
      type: "technical"
      config:
        cpu_threshold: 80
        memory_threshold: 2048
    - name: "ethical_compliance"
      type: "ethical"
      config:
        bias_detection_threshold: 0.1
        transparency_requirement: true

# Execution configuration
execution:
  runs_per_scenario: 5
  max_duration: 3600  # 1 hour
  timeout: 600
  retry_on_failure: true
  max_retries: 5
  warmup_runs: 1

# Output configuration
output:
  format: "json"
  path: "./advanced_results"
  include_detailed_logs: true
  include_audit_trail: true
  export_formats:
    - "json"
    - "csv"
    - "html"

# Validation configuration
validation:
  enabled: true
  statistical_significance: true
  confidence_level: 0.99
  reproducibility_check: true
  cross_validation: true
  outlier_detection: true

# Monitoring and observability
monitoring:
  enabled: true
  metrics_interval: 10
  log_level: "INFO"
  performance_tracking: true
  resource_monitoring: true

# Metadata
metadata:
  author: "FBA-Bench Team"
  created: "2025-01-01T00:00:00Z"
  tags: ["advanced", "comprehensive", "multi-domain", "production"]
  requirements:
    - "High-performance computing environment"
    - "Multiple LLM model access"
    - "Large storage capacity for results"
  notes: "This configuration is designed for comprehensive benchmarking across multiple domains and agent types."