# Memory Experiment Configuration: Ablated Memory (7-day retention)
# Tests agent performance with limited memory window to measure memory dependency

# Base constraint configuration
budget_constraints:
  max_tokens_per_action: 16000
  max_total_tokens: 500000
  token_cost_per_1k: 0.06
  violation_penalty_weight: 2.0
  grace_period_percentage: 5.0

enforcement:
  hard_fail_on_violation: true
  inject_budget_status: true
  track_token_efficiency: true

# Memory-specific configuration
memory_configuration:
  memory_mode: "short_term_only"
  
  # Short-term memory settings (limited retention)
  short_term_capacity: 50
  short_term_retention_days: 7
  short_term_decay_function: "linear"
  
  # Long-term memory disabled for ablation
  long_term_capacity: 0
  long_term_retention_days: null
  long_term_decay_function: "none"
  
  # Reflection disabled for pure ablation
  reflection_enabled: false
  reflection_frequency_hours: 24
  consolidation_algorithm: "importance_score"
  consolidation_percentage: 0.0
  
  # Memory retrieval settings
  max_retrieval_events: 15
  retrieval_relevance_threshold: 0.7
  
  # Vector store configuration
  vector_store_enabled: true
  vector_store_backend: "faiss"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vector_dimension: 384
  
  # Memory injection settings
  enable_memory_injection: true
  memory_budget_tokens: 1500
  track_memory_usage: true
  
  # Domain configuration
  memory_domains: ["pricing", "sales", "competitors", "strategy", "operations"]
  domain_specific_retention: {}

# Experiment metadata
experiment_metadata:
  name: "Ablated Memory Experiment"
  description: "Tests agent performance with 7-day memory retention to measure memory dependency"
  purpose: "Establish baseline for memory vs. reasoning attribution"
  expected_outcome: "Performance drop indicates memory dependency"