# Memory Experiment Configuration: Memory-Free Baseline
# Tests agent performance without any memory assistance for pure reasoning baseline

# Base constraint configuration
budget_constraints:
  max_tokens_per_action: 16000
  max_total_tokens: 500000
  token_cost_per_1k: 0.06
  violation_penalty_weight: 2.0
  grace_period_percentage: 5.0

enforcement:
  hard_fail_on_violation: true
  inject_budget_status: true
  track_token_efficiency: true

# Memory-specific configuration
memory_configuration:
  memory_mode: "memory_free"
  
  # All memory disabled
  short_term_capacity: 0
  short_term_retention_days: 0
  short_term_decay_function: "none"
  
  long_term_capacity: 0
  long_term_retention_days: null
  long_term_decay_function: "none"
  
  # No reflection or consolidation
  reflection_enabled: false
  reflection_frequency_hours: 24
  consolidation_algorithm: "importance_score"
  consolidation_percentage: 0.0
  
  # Minimal retrieval settings
  max_retrieval_events: 0
  retrieval_relevance_threshold: 1.0
  
  # Vector store disabled
  vector_store_enabled: false
  vector_store_backend: "faiss"
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  vector_dimension: 384
  
  # No memory injection
  enable_memory_injection: false
  memory_budget_tokens: 0
  track_memory_usage: true
  
  # No domain memory
  memory_domains: []
  domain_specific_retention: {}

# Experiment metadata
experiment_metadata:
  name: "Memory-Free Baseline Experiment"
  description: "Tests pure reasoning ability without any memory assistance"
  purpose: "Establish baseline for measuring memory vs. reasoning contributions"
  expected_outcome: "Lowest performance scores - pure reasoning capability"