# Development environment configuration
# This configuration is optimized for development and debugging

environment:
  deterministic: true
  random_seed: 42
  parallel_execution: false
  max_workers: 1
  debug_mode: true

execution:
  runs_per_scenario: 1
  max_duration: 0  # Unlimited for development
  timeout: 600
  retry_on_failure: false
  max_retries: 0

output:
  format: "json"
  path: "./dev_results"
  include_detailed_logs: true
  include_audit_trail: true
  console_output: true

validation:
  enabled: true
  statistical_significance: false  # Skip for single runs
  confidence_level: 0.95
  reproducibility_check: true

monitoring:
  enabled: true
  metrics_interval: 5
  log_level: "DEBUG"
  performance_tracking: true
  resource_monitoring: false
  debug_tracing: true

# Development-specific settings
development:
  hot_reload: true
  auto_save: true
  breakpoint_support: true
  test_mode: true
  mock_external_services: true
  verbose_logging: true
  profiling:
    enabled: true
    output_format: "html"
    include_memory: true
    include_cpu: true