# Production environment configuration
# This configuration is optimized for production benchmarking runs

environment:
  deterministic: true
  random_seed: null  # Use system-generated seed for production
  parallel_execution: true
  max_workers: 8
  debug_mode: false

execution:
  runs_per_scenario: 10
  max_duration: 7200  # 2 hours
  timeout: 900
  retry_on_failure: true
  max_retries: 3
  warmup_runs: 2

output:
  format: "json"
  path: "./production_results"
  include_detailed_logs: false
  include_audit_trail: true
  console_output: false
  export_formats:
    - "json"
    - "csv"
    - "parquet"
  compression: true
  backup_results: true
  retention_days: 90

validation:
  enabled: true
  statistical_significance: true
  confidence_level: 0.99
  reproducibility_check: true
  cross_validation: true
  outlier_detection: true
  data_quality_checks: true

monitoring:
  enabled: true
  metrics_interval: 30
  log_level: "WARNING"
  performance_tracking: true
  resource_monitoring: true
  alert_thresholds:
    cpu_usage: 95
    memory_usage: 90
    execution_time: 3600
    error_rate: 0.05
  alerts:
    enabled: true
    channels:
      - "email"
      - "slack"
      - "pagerduty"
    escalation_policy: true

# Production-specific settings
production:
  high_availability: true
  distributed_execution: true
  load_balancing: true
  auto_scaling: true
  security:
    encryption: true
    access_control: true
    audit_logging: true
    data_retention_policy: true
  performance:
    optimization_level: "high"
    caching_enabled: true
    connection_pooling: true
  backup:
    enabled: true
    schedule: "daily"
    retention: "30d"
    offsite_storage: true
  compliance:
    gdpr_compliant: true
    data_privacy: true
    audit_trail: true
    version_control: true
  cost_optimization:
    spot_instances: true
    auto_shutdown: true
    resource_monitoring: true
    cost_alerts: true