# Testing environment configuration
# This configuration is optimized for automated testing and CI/CD

environment:
  deterministic: true
  random_seed: 12345
  parallel_execution: true
  max_workers: 2
  debug_mode: false

execution:
  runs_per_scenario: 3
  max_duration: 1800  # 30 minutes
  timeout: 300
  retry_on_failure: true
  max_retries: 2
  warmup_runs: 0

output:
  format: "json"
  path: "./test_results"
  include_detailed_logs: true
  include_audit_trail: true
  console_output: false
  test_report_format: "junit"

validation:
  enabled: true
  statistical_significance: true
  confidence_level: 0.95
  reproducibility_check: true
  cross_validation: true

monitoring:
  enabled: true
  metrics_interval: 10
  log_level: "INFO"
  performance_tracking: true
  resource_monitoring: true
  alert_thresholds:
    cpu_usage: 90
    memory_usage: 80
    execution_time: 600

# Testing-specific settings
testing:
  automated: true
  ci_cd_integration: true
  test_suites:
    - "unit_tests"
    - "integration_tests"
    - "performance_tests"
  test_data:
    use_mock_data: true
    data_size: "small"
  reporting:
    generate_html_report: true
    generate_xml_report: true
    include_coverage: true
  quality_gates:
    min_success_rate: 0.95
    max_execution_time: 1800
    max_memory_usage: 2048
  notifications:
    on_failure: true
    on_success: false
    channels:
      - "email"
      - "slack"