# Example Cognitive Agent Configuration

cognitive_system:
  enabled: true

  # Hierarchical Planning Configuration
  hierarchical_planning:
    enabled: true
    depth: 2 # Annual goals -> Quarterly plans
    goal_horizon: "annual"
    replan_frequency: "end_of_quarter"
    lookahead_days: 90
    llm_model: "gpt-4o" # Use a capable model for planning
    prompt_template: "hierarchical_planning_v1" # Assuming a template exists

  # Reflection System Configuration
  reflection:
    enabled: true
    frequency: "end_of_quarter" # Reflect after each quarter's results
    insight_generation: true
    feedback_loop_enabled: true
    max_reflection_tokens: 3000
    min_progress_for_reflection: 0.10 # Reflect if KPIs change by more than 10%
    llm_model: "claude-3-opus" # Use a robust model for reflection
    prompt_template: "structured_reflection_v1"

  # Memory Management Configuration
  memory:
    enabled: true
    validation: true # Actively check memory consistency
    consistency_checks: true # Prevents contradictory info
    forgetting_strategy: "least_recent_access" # Prune oldest/least used memories
    max_memory_size: 500 # Keep short-term memory lean
    long_term_storage_backend: "json_file" # Or "database", "vector_db" if setup
    memory_path: "./memory_data/cognitive_agent/" # Dedicated path for this agent's memory
    llm_model: "gpt-3.5-turbo" # Cheaper model for summarization/rewriting memory