budget_constraints:
  max_tokens_per_action: 128000
  max_total_tokens: 5000000
  token_cost_per_1k: 0.20  # USD
  violation_penalty_weight: 3.0
  grace_period_percentage: 5.0
enforcement:
  hard_fail_on_violation: true
  inject_budget_status: true
  track_token_efficiency: true